name: remove-lean-core-branch

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/remove-lean-core-branch.yml

permissions:
  contents: write

jobs:
  remove:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Remove obsolete branch
        run: git push origin --delete agent/lean-core
